# Generated by Django 5.0.1 on 2024-02-07 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_item_filters'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrandValues',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title1', models.CharField(max_length=12)),
                ('title2', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='ColorValues',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='FabricValues',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='OccasionValues',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PatternValues',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SeasonValues',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SleeveLengthValues',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='filter',
            name='value',
        ),
        migrations.RemoveField(
            model_name='item',
            name='filters',
        ),
        migrations.AddField(
            model_name='item',
            name='discount_percent',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='item',
            name='discount_price',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='item',
            name='likes',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='item',
            name='original_price',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='item',
            name='brand_filter',
            field=models.ManyToManyField(blank=True, to='items.brandvalues'),
        ),
        migrations.AddField(
            model_name='item',
            name='color_filter',
            field=models.ManyToManyField(blank=True, to='items.colorvalues'),
        ),
        migrations.AddField(
            model_name='item',
            name='fabric_filter',
            field=models.ManyToManyField(blank=True, to='items.fabricvalues'),
        ),
        migrations.AddField(
            model_name='item',
            name='occasion_filter',
            field=models.ManyToManyField(blank=True, to='items.occasionvalues'),
        ),
        migrations.AddField(
            model_name='item',
            name='pattern_filter',
            field=models.ManyToManyField(blank=True, to='items.patternvalues'),
        ),
        migrations.AddField(
            model_name='item',
            name='season_filter',
            field=models.ManyToManyField(blank=True, to='items.seasonvalues'),
        ),
        migrations.AddField(
            model_name='item',
            name='sleeve_length_filter',
            field=models.ManyToManyField(blank=True, to='items.sleevelengthvalues'),
        ),
        migrations.DeleteModel(
            name='Values',
        ),
        migrations.DeleteModel(
            name='Filter',
        ),
    ]
