# Generated by Django 5.0.1 on 2024-02-07 19:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0005_alter_item_discount_price_alter_item_original_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='brand_filter',
        ),
        migrations.RemoveField(
            model_name='item',
            name='color_filter',
        ),
        migrations.RemoveField(
            model_name='item',
            name='fabric_filter',
        ),
        migrations.RemoveField(
            model_name='item',
            name='occasion_filter',
        ),
        migrations.RemoveField(
            model_name='item',
            name='pattern_filter',
        ),
        migrations.RemoveField(
            model_name='item',
            name='season_filter',
        ),
        migrations.RemoveField(
            model_name='item',
            name='sleeve_length_filter',
        ),
        migrations.AddField(
            model_name='item',
            name='brand_filter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='items.brandvalues'),
        ),
        migrations.AddField(
            model_name='item',
            name='color_filter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='items.colorvalues'),
        ),
        migrations.AddField(
            model_name='item',
            name='fabric_filter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='items.fabricvalues'),
        ),
        migrations.AddField(
            model_name='item',
            name='occasion_filter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='items.occasionvalues'),
        ),
        migrations.AddField(
            model_name='item',
            name='pattern_filter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='items.patternvalues'),
        ),
        migrations.AddField(
            model_name='item',
            name='season_filter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='items.seasonvalues'),
        ),
        migrations.AddField(
            model_name='item',
            name='sleeve_length_filter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='items.sleevelengthvalues'),
        ),
    ]
