# Generated by Django 5.0.1 on 2024-02-10 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0007_category_created_at_item_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='item_images/'),
        ),
        migrations.AlterField(
            model_name='category',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='discount_percent',
            field=models.PositiveIntegerField(default=5),
        ),
    ]
