# Generated by Django 5.0.1 on 2024-02-12 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0008_item_image_alter_category_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='brand_filter',
        ),
        migrations.RemoveField(
            model_name='item',
            name='color_filter',
        ),
        migrations.RemoveField(
            model_name='item',
            name='fabric_filter',
        ),
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.FileField(null=True, upload_to='item_images/'),
        ),
        migrations.RemoveField(
            model_name='item',
            name='occasion_filter',
        ),
        migrations.RemoveField(
            model_name='item',
            name='pattern_filter',
        ),
        migrations.RemoveField(
            model_name='item',
            name='season_filter',
        ),
        migrations.RemoveField(
            model_name='item',
            name='sleeve_length_filter',
        ),
        migrations.AlterField(
            model_name='item',
            name='title',
            field=models.CharField(max_length=45),
        ),
        migrations.AddField(
            model_name='item',
            name='brand_filter',
            field=models.ManyToManyField(blank=True, null=True, to='items.brandvalues'),
        ),
        migrations.AddField(
            model_name='item',
            name='color_filter',
            field=models.ManyToManyField(blank=True, null=True, to='items.colorvalues'),
        ),
        migrations.AddField(
            model_name='item',
            name='fabric_filter',
            field=models.ManyToManyField(blank=True, null=True, to='items.fabricvalues'),
        ),
        migrations.AddField(
            model_name='item',
            name='occasion_filter',
            field=models.ManyToManyField(blank=True, null=True, to='items.occasionvalues'),
        ),
        migrations.AddField(
            model_name='item',
            name='pattern_filter',
            field=models.ManyToManyField(blank=True, null=True, to='items.patternvalues'),
        ),
        migrations.AddField(
            model_name='item',
            name='season_filter',
            field=models.ManyToManyField(blank=True, null=True, to='items.seasonvalues'),
        ),
        migrations.AddField(
            model_name='item',
            name='sleeve_length_filter',
            field=models.ManyToManyField(blank=True, null=True, to='items.sleevelengthvalues'),
        ),
    ]
