# Generated by Django 5.0.1 on 2024-02-13 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0009_remove_item_brand_filter_remove_item_color_filter_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='brand_filter',
            field=models.ManyToManyField(blank=True, to='items.brandvalues'),
        ),
        migrations.AlterField(
            model_name='item',
            name='color_filter',
            field=models.ManyToManyField(blank=True, to='items.colorvalues'),
        ),
        migrations.AlterField(
            model_name='item',
            name='discount_price',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='item',
            name='fabric_filter',
            field=models.ManyToManyField(blank=True, to='items.fabricvalues'),
        ),
        migrations.AlterField(
            model_name='item',
            name='occasion_filter',
            field=models.ManyToManyField(blank=True, to='items.occasionvalues'),
        ),
        migrations.AlterField(
            model_name='item',
            name='original_price',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='item',
            name='pattern_filter',
            field=models.ManyToManyField(blank=True, to='items.patternvalues'),
        ),
        migrations.AlterField(
            model_name='item',
            name='season_filter',
            field=models.ManyToManyField(blank=True, to='items.seasonvalues'),
        ),
        migrations.AlterField(
            model_name='item',
            name='sleeve_length_filter',
            field=models.ManyToManyField(blank=True, to='items.sleevelengthvalues'),
        ),
    ]
